### PR TITLE
large array of ultrasonic atomizers used as display

### PR DESCRIPTION
**Pull request by stephanschulz**
Your survey is awesome and a create resource for future artworks.
For many years we have used atomizers to create DMX controlled interactive displays. I thought it might be of interest to you.

Thanks for your great work.
Stephan.

### CODE REVIEW

**Comment by laserpilot** [comment]
thank you for this comment and addition! I realized I haven't yet thought about the appropriate method for adding pull requests and content updates, so thank you for a very early submission. Give me a few days to review and think about if I have any questions. One thing I need to figure out are whether I prefer all images to be embedded as part of the repo or if external links are ok (since all the videos are obviously external) and then how to let people do that without the access to the gitbook editing feature. I really almost went with putting this all on Notion like Anti-modular, but I wanted it to be markdown so it's easily portable when tools like that go offline.

Additionally - your addition for ultrasonic misters is very interesting and should absolutely be included, but at first glance would you be open to including it as a sub category in the "Projection on water or fog" technique area instead of its own page for now? I was trying to keep the top categories a little more simplified. Open to discuss more once I think of other questions before merging. Thank you!

**Comment by stephanschulz** [comment]
Please take all the time in the world. You created a great resource and should shape it the way you feel it needs to be.
Notion is great but i do like how gitbook makes the process of suggesting additions much easier.

About your question on adding it to "Projection on water or fog".
Rafael feels very strongly about it not being part of this category and says there is no projection. Our pieces are literally pixelated vapour displays and that’s how they need to be presented, the tradition of projection into water is long standing and not particularly different than any other projection.
I hope this works for you.
All the best.

**Comment by laserpilot** [comment]
Hey Stephen - thank you! I just added some updates notes on my contribution preferences. I neglected to actually look at your links before I commented and didnt realize how the atomizer screen worked - so cool! Great reference. My only comment now is that I think it might be a better fit for the "Experimental/Other" category as its own page, or putting it in the "Mechanical/Physical Display" sub section in there. I'm trying to keep the Alternative Displays section as more of a commercial product kind of space as much as I can, even though my own categories don't always make sense to me. Open to suggestions there. Maybe I should rename Experimental/Other to something like Artworks and Experimental. 

The only other note would be to add the images directly to the repo instead of them being a linkout - they would go in .gitbook/assets and have a relative path. Thanks again!

**Comment by laserpilot** [comment]
@stephanschulz let me know if you have any thoughts on moving the location of the submission and re-submitting or if I should move it around. I'd love to get this included, just didnt want to leave it sitting for too long.

**Comment by stephanschulz** [comment]
sorry about the late reply. 
let's do it as you are suggesting, I am sure it will be great.
:)

**Comment by stephanschulz** [comment]
Hi. Did you find the time to include the projects in to your very comprehensive survey?

**Comment by laserpilot** [comment]
Ah no, sorry, this fell off my to-do list. I'm going to edit it now

**Comment by laserpilot** [comment]
Ok - I manually updated this because I couldn't figure out the right way to combine your edit in there and I also made some formatting changes but preserved most of the content. I'm going to close the pull request for now, but it's currently in here: https://app.gitbook.com/s/G7i5jnXrJr1PuTtrROZh/experimental-other/ultrasonic-atomization-of-water

**Comment by stephanschulz** [comment]
nice.
can you please correct Raphael and Rahael to Rafael. 
Thanks for your great work.

**Comment by laserpilot** [comment]
ah yes, apologies, I have a friend named Raphael and he was clearly on my mind 😅 - all fixed now

**Pull request closed without merging**
